### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by Fahaxikiii** [JustUndertaker/tuanzi_bot#3]
请教，发送色图命令之后怎么修改文件能发送图片而不是链接。

**Comment by JustUndertaker** [comment]
> 请教，发送色图命令之后怎么修改文件能发送图片而不是链接。

这个项目是以前练手用的，已经很久没有维护了，如果需要可以参考nonebot2插件商店：https://v2.nonebot.dev/store.html
这里应该有你想要的东西。

**Comment by Fahaxikiii** [comment]
> > 请教，发送色图命令之后怎么修改文件能发送图片而不是链接。
> 
> 这个项目是以前练手用的，已经很久没有维护了，如果需要可以参考nonebot2插件商店：https://v2.nonebot.dev/store.html 这里应该有你想要的东西。

好的，谢谢
